/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 gauges.glb -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    digitalIn: THREE.Mesh
    digitalOut: THREE.Mesh
    levelMeasures: THREE.Mesh
    cyclic: THREE.Mesh
    cyclicMesures: THREE.Mesh
    level: THREE.Mesh
  }
  materials: {}
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/gauges.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.digitalIn.geometry} material={nodes.digitalIn.material} position={[10.984, 16.551, -7.627]} />
      <mesh geometry={nodes.digitalOut.geometry} material={nodes.digitalOut.material} position={[-6.899, 1.505, -7.583]} />
      <mesh geometry={nodes.levelMeasures.geometry} material={nodes.levelMeasures.material} position={[12.469, 6.231, -7.879]} />
      <mesh geometry={nodes.cyclic.geometry} material={nodes.cyclic.material} position={[1.856, 14.577, -8.634]} />
      <mesh geometry={nodes.cyclicMesures.geometry} material={nodes.cyclicMesures.material} position={[1.856, 14.568, -8.746]} />
      <mesh geometry={nodes.level.geometry} material={nodes.level.material} position={[12.907, 0.474, -7.875]} />
    </group>
  )
}

useGLTF.preload('/gauges.glb')
